import { breadcrumbJsonLd,buildMetadata,serviceJsonLd } from "@/lib/seo";
import { PageHero } from "@/components/layout/PageHero";
import { Section } from "@/components/ui/Section";
import { Button } from "@/components/ui/Button";
import { Breadcrumbs } from "@/components/seo/Breadcrumbs";

const path="/industries/medical-dental-clinics";
export const metadata=buildMetadata({title:"Medical, Dental & Aesthetic Clinic Automation Toronto",path,description:"Workflow automation for Toronto medical, dental, med spa, and aesthetic clinics—focused on inquiries, appointments, follow-up, and administration."});
const frictions=["Delayed responses when staff are serving patients or clients","Manual appointment reminders and repeated scheduling coordination","Missed follow-up after an inquiry or consultation request","Repetitive intake administration and information re-entry","Client and operational information divided across inboxes, forms, and systems","Limited visibility into where inquiries, staff capacity, or next actions are lost"];
export default function ClinicPage(){return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([serviceJsonLd({name:"Clinic workflow automation",description:"Workflow assessment and automation for medical, dental, med spa, and aesthetic clinics.",path,audience:"Clinic operators in Toronto and Ontario"}),breadcrumbJsonLd([{name:"Home",path:"/"},{name:"Industries",path:"/industries"},{name:"Medical, dental, and aesthetic clinics",path}])])}}/><Breadcrumbs items={[{name:"Home",path:"/"},{name:"Industries",path:"/industries"},{name:"Clinics",path}]}/><PageHero eyebrow="Clinic automation" title="Reduce administrative friction without removing human authority." lead="Regulus examines how inquiries, appointments, follow-up, intake, and operational information move through a clinic. Medical, dental, med spa, and aesthetic workflows differ; the system must fit the actual practice."/><Section><div className="grid gap-10 lg:grid-cols-2"><div><h2 className="text-h2">Where administrative time can disappear</h2><ul className="mt-6 space-y-4 text-ink-soft">{frictions.map(x=><li key={x}>• {x}</li>)}</ul></div><div className="rounded-3xl border border-line bg-panel p-8"><h2 className="text-h2">How potential automation is approached</h2><p className="mt-4 text-ink-soft">We observe the existing workflow, establish what can be measured, identify unknowns, and define a bounded first improvement. No outcome is promised before discovery and a baseline.</p><p className="mt-5 text-ink-soft">Systems are designed around the clinic’s existing workflow, consent requirements, privacy obligations, and human decision authority. Regulus does not provide legal or regulatory assurances.</p><Button href="/automation/automation-opportunity-audit" variant="secondary" className="mt-7">Review the Automation Opportunity Audit</Button><Button href="/contact?intent=clinic-automation" className="mt-3" data-analytics-event="audit_inquiry">Discuss a clinic workflow</Button></div></div></Section></>}
