import { articleJsonLd,breadcrumbJsonLd,buildMetadata } from "@/lib/seo";
import { ArticleShell } from "@/components/seo/ArticleShell";
const path="/insights/where-clinics-lose-administrative-time",date="July 23, 2026";
const title="Where Medical and Dental Clinics Commonly Lose Administrative Time";
const description="Clinic administrative time can be lost in inquiry response, scheduling coordination, intake handling, follow-up, information re-entry, and unclear ownership.";
export const metadata=buildMetadata({title,path,description,type:"article",publishedTime:"2026-07-23",modifiedTime:"2026-07-23"});
export default function Article(){return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([articleJsonLd({headline:title,description,path,published:"2026-07-23",modified:"2026-07-23"}),breadcrumbJsonLd([{name:"Home",path:"/"},{name:"Insights",path:"/insights"},{name:title,path}])])}}/><ArticleShell title={title} summary={description} published={date} cta="/industries/medical-dental-clinics">
<section><h2 className="text-h2 text-ink">The recurring pattern is movement between responsibilities</h2><p className="mt-4">Administrative loss often appears between systems or roles: a call becomes a note, a note becomes a task, a form becomes re-entered data, or an unanswered question waits without a visible owner. This is a diagnostic pattern, not a claim about every clinic.</p></section>
<section><h2 className="text-h2 text-ink">Inquiry response</h2><p className="mt-4">Calls and forms may arrive while staff are assisting people in the clinic. Measure acknowledgement time, unanswered inquiries, and the path from first contact to accountable follow-up before deciding whether automation is useful.</p></section>
<section><h2 className="text-h2 text-ink">Appointment coordination and reminders</h2><p className="mt-4">Repeated calls, emails, confirmations, and rescheduling can create avoidable handling. The relevant evidence includes how requests enter, what information is missing, where human approval is necessary, and how exceptions are resolved.</p></section>
<section><h2 className="text-h2 text-ink">Intake and information re-entry</h2><p className="mt-4">Information may move from a form to an inbox, practice system, spreadsheet, or note. A workflow review should map the movement without collecting unnecessary clinical or personal information.</p></section>
<section><h2 className="text-h2 text-ink">Follow-up and ownership</h2><p className="mt-4">A next action that depends on memory is difficult to measure. A useful system makes the approved action, responsible person, due time, completion state, and exception visible while keeping judgment with clinic staff.</p></section>
<section><h2 className="text-h2 text-ink">What must remain unknown until discovery</h2><p className="mt-4">The volume of lost time, financial effect, suitability of any integration, and expected result are unknown without clinic-specific evidence. Medical, dental, med spa, and aesthetic practices also differ in service model and operating obligations. Design must follow the actual workflow, consent requirements, privacy obligations, and human decision authority.</p></section>
</ArticleShell></>}
