import { getStore } from "@netlify/blobs";
import { createLeadRecord,opaqueLeadKey,validateLead,type LeadInput } from "@/lib/leads";
export const runtime="nodejs";export const dynamic="force-dynamic";
const headers={"Cache-Control":"no-store","X-Robots-Tag":"noindex, nofollow, noarchive"};
const ip=(r:Request)=>r.headers.get("x-nf-client-connection-ip")||r.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"";
async function notify(record:ReturnType<typeof createLeadRecord>){const url=process.env.LEAD_NOTIFICATION_WEBHOOK_URL;if(!url)return "NOT_CONFIGURED";try{await fetch(url,{method:"POST",headers:{"Content-Type":"application/json",...(process.env.LEAD_NOTIFICATION_WEBHOOK_TOKEN?{Authorization:`Bearer ${process.env.LEAD_NOTIFICATION_WEBHOOK_TOKEN}`}:{})},body:JSON.stringify({event:"regulus.lead.created",recipient:"info@regulusautomation.ca",lead:record}),signal:AbortSignal.timeout(5000)});return "SENT";}catch{return "FAILED";}}
export async function POST(request:Request){const origin=request.headers.get("origin");const host=request.headers.get("host");if(origin&&host&&new URL(origin).host!==host)return Response.json({ok:false,error:"Invalid request origin."},{status:403,headers});let body:LeadInput;try{body=await request.json();}catch{return Response.json({ok:false,error:"Invalid request."},{status:400,headers});}const v=validateLead(body);if(v.bot)return Response.json({ok:true,received:true},{headers});if(!v.ok)return Response.json({ok:false,field_errors:v.errors},{status:400,headers});
 try{const salt=process.env.LEAD_RATE_LIMIT_SALT||"";if(salt.length<32)return Response.json({ok:false,error:"Lead service is not configured."},{status:503,headers});const store=getStore({name:"regulus-inbound-leads",consistency:"strong"});const rate=getStore({name:"regulus-lead-rate-limits",consistency:"strong"});const client=ip(request);if(client){const bucket=Math.floor(Date.now()/3_600_000);const key=`${bucket}:${opaqueLeadKey(client,salt)}`;const old=await rate.get(key,{type:"json"}).catch(()=>null) as {count?:number}|null;if((old?.count||0)>=5)return Response.json({ok:false,error:"Please try again later."},{status:429,headers});await rate.setJSON(key,{count:(old?.count||0)+1});}
 const duplicate=opaqueLeadKey(`${v.value.email}|${v.value.value_leak_description}`,salt);const prior=await store.get(`duplicates/${duplicate}`);if(prior)return Response.json({ok:true,received:true,duplicate:true},{headers});const record=createLeadRecord(v.value);await store.setJSON(`leads/${record.lead_id}`,record);await store.set(`duplicates/${duplicate}`,record.lead_id);const notification_status=await notify(record);await store.setJSON(`events/${record.lead_id}`,{lead_id:record.lead_id,notification_status,at:new Date().toISOString()});return Response.json({ok:true,received:true,lead_id:record.lead_id,notification_status},{status:201,headers});
 }catch{return Response.json({ok:false,error:"We couldn’t submit your request. Please try again."},{status:503,headers});}}
