import { articleJsonLd,breadcrumbJsonLd,buildMetadata } from "@/lib/seo";
import { ArticleShell } from "@/components/seo/ArticleShell";
const path="/insights/how-to-identify-workflows-worth-automating",date="July 23, 2026";
const title="How to Identify Workflows Worth Automating";
const description="Start with repeated, observable work that has stable inputs, visible delays, measurable volume, and a clear human owner—not with a technology.";
export const metadata=buildMetadata({title,path,description,type:"article",publishedTime:"2026-07-23",modifiedTime:"2026-07-23"});
export default function Article(){return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([articleJsonLd({headline:title,description,path,published:"2026-07-23",modified:"2026-07-23"}),breadcrumbJsonLd([{name:"Home",path:"/"},{name:"Insights",path:"/insights"},{name:title,path}])])}}/><ArticleShell title={title} summary={description} published={date}>
<section><h2 className="text-h2 text-ink">Begin with the work, not the tool</h2><p className="mt-4">A workflow is a good automation candidate when its current path can be described and observed. “Use AI for administration” is not a workflow. “Classify each new inquiry, acknowledge receipt, and route it to an accountable queue” is.</p></section>
<section><h2 className="text-h2 text-ink">Five signals worth examining</h2><ol className="mt-4 space-y-4"><li><strong className="text-ink">Repetition:</strong> the same handling occurs often enough to observe.</li><li><strong className="text-ink">Stable inputs:</strong> the information entering the process has recognizable forms.</li><li><strong className="text-ink">Visible delay or rework:</strong> waiting, copying, searching, or correction can be identified.</li><li><strong className="text-ink">Measurable state:</strong> the organization can tell whether an item is new, waiting, complete, or exceptional.</li><li><strong className="text-ink">Human ownership:</strong> someone remains accountable for exceptions and consequential decisions.</li></ol></section>
<section><h2 className="text-h2 text-ink">Measure the baseline before proposing an outcome</h2><p className="mt-4">Useful baselines can include elapsed time, manual steps, handoffs, open items, exceptions, and missing information. If those facts are unavailable, the honest state is unknown. An initial observation period may be more valuable than immediate implementation.</p></section>
<section><h2 className="text-h2 text-ink">Separate observation, assumption, and illustration</h2><p className="mt-4"><strong className="text-ink">Observation</strong> is supported by a source. <strong className="text-ink">Assumption</strong> is a proposition to test. <strong className="text-ink">Illustration</strong> explains a method but is not evidence about the organization. Keeping these distinct prevents a plausible story from becoming an unsupported business case.</p></section>
<section><h2 className="text-h2 text-ink">Choose a bounded first workflow</h2><p className="mt-4">Prefer a workflow with a clear start, finish, owner, exception path, and rollback. The goal is not maximum automation. It is a reliable improvement whose effect can be evaluated without obscuring responsibility.</p></section>
</ArticleShell></>}
